server:
  servlet:
    context-path: /venue-hub-api
  port: 8080
  error:
    include-stacktrace: never

spring:
  application:
    name: venue-hub-api

  datasource:
    url: ${DB_HOST}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update